blog/urls.py
from django.urls import path
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.CharField(max_length=200, verbose_name='Slug')
    body = models.TextField(verbose_name='Содержание')
    preview = models.ImageField(upload_to='blog_images/', verbose_name='Превью')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания', blank=True, null=True)
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано', blank=True, null=True)
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров', blank=True, null=True)

    def str(self):
        return (f'{self.title} '
                f'{self.slug} '
                f'{self.body} '
                f'{self.preview} '
                f'{self.created_at} '
                f'{self.is_published} '
                f'{self.views_count} '
                f'')

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from .models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ['title', 'body', 'preview', 'is_published']
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    context_object_name = 'object_list'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'
    context_object_name = 'object'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'body', 'preview', 'is_published']
    template_name = 'blog/blog_form.html'

    def form_valid(self, form):
        if form.is_valid():
            updated_blog = form.save(commit=False)
            updated_blog.slug = slugify(updated_blog.title)
            updated_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blog/blog_confirm_delete.html'
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends "categories.html" %}
{% block content %}
<div class="container">
    <h1>Удалить {{ object.title }}?</h1>
    <p>Вы уверены, что хотите удалить этот блог?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
    <a href="{% url 'blog:list' %}" class="btn btn-outline-secondary">Отмена</a>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "categories.html" %}
{% block content %}
<div class="container">
    <h1>{{ object.title }}({{ object.slug }})</h1>
    <img src="{{ object.preview.url }}" alt="{{ object.title }}" class="img-fluid">
    <p>{{ object.body }}</p>
    <div class="d-flex justify-content-between">
        <a href="{% url 'blog:update' object.pk %}" class="btn btn-warning">Редактировать</a>
        Просмотры: {{ object.views_count }}
        <a href="{% url 'blog:list' %}" class="btn btn-outline-secondary">Назад к списку</a>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "categories.html" %}
{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <h2>{% if object %}Редактировать{% else %}Создать{% endif %} Блог</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
                <a href="{% url 'blog:list' %}" class="btn btn-outline-secondary">Назад к списку</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "categories.html" %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить материал</a>
</div>
<div class="container">
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img src="{{ object.preview.url }}" alt="{{ object.title }}" class="card-img-top" style="width: 100%; height: auto;">
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <p class="card-text">{{ object.body|truncatewords:20 }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blog:detail' object.pk %}" class="btn btn-info">Просмотр</a>
                            <a href="{% url 'blog:update' object.pk %}" class="btn btn-primary">Редактировать</a>
                            <a href="{% url 'blog:delete' object.pk %}" class="btn btn-danger">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}